[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hops"
version = "0.1.0"
description = "Your project description here"
authors = [{name = "Andrew Morrison", email = "asm@w2asm.com"}]

[project.scripts]
hops = "hops.cli:main"
